### ISSUE TITLE
MSRV for this crate?

### ISSUE THREAD

**Issue by TonalidadeHidrica** [ruuda/claxon#28]
I'm thinking of contributing this crate (specifically, add seek feature!).  Do you have MSRV for this crate in mind?  Also, do I have to stick to Edition 2015 instead of the latest 2018?

**Comment by ruuda** [comment]
The current minimum supported Rust version is 1.13. It’s also mentioned per version in the changelog. I wouldn’t be opposed to bumping it if there’s a good reason for it, but I generally try to keep it conservative (e.g. the minimum one shipped by supported version of a widely used distro).

I did some work on the [`metadata3` branch](https://github.com/ruuda/claxon/tree/metadata3) recently (my third attempt at a good way to support reading metadata in a way that is both flexible and performant); there I bumped the minimum supported version to 1.34.2 (used by Debian Jessie at the moment). I plan for this branch to eventually become the next version, but currently it has some performance regressions due to switching the reader traits that I still need to fix.

> specifically, add seek feature

Great that you ant to work on this! It sounds like this could be a big feature, it would be good to open an issue in advance with some high-level plans, before making a big PR.

**Comment by ruuda** [comment]
The current minimum supported Rust version is 1.13. It’s also mentioned per version in the changelog. I wouldn’t be opposed to bumping it if there’s a good reason for it, but I generally try to keep it conservative (e.g. the minimum one shipped by supported version of a widely used distro).

I did some work on the [`metadata3` branch](https://github.com/ruuda/claxon/tree/metadata3) recently (my third attempt at a good way to support reading metadata in a way that is both flexible and performant); there I bumped the minimum supported version to 1.34.2 (used by Debian Jessie at the moment). I plan for this branch to eventually become the next version, but currently it has some performance regressions due to switching the reader traits that I still need to fix.

> specifically, add seek feature

Great that you ant to work on this! It sounds like this could be a big feature, it would be good to open an issue in advance with some high-level plans, before making a big PR.

**Comment by TonalidadeHidrica** [comment]
Thanks for your reply.  Generally I prefer higher versions because it has cleverer borrow checkers and nice new standard functions and syntaxes.  But well, I'll stick to 1.13 as much as possible until it becomes serious burden.

I'll also create a tracking issues for seeking.  Yes, it'd indeed be a big changes, and it will include several steps.  I'll open an issue as long as it's ready.  Thank you for your answer and suggestion!
